variables:
  PROJECT_NAME: BallDragDrop
  PROJECT_RESULTS_NAME: BallDragDrop.WPF
before_script:
  - echo "starting build for $PROJECT_NAME"
  - echo "Restoring NuGet Packages..."
  - dotnet restore "src/$PROJECT_NAME.sln"
stages:
  - build
  - code-quality
  - test
build:
  tags:
  - c#
  - windows
  stage: build
  script:
  - echo "Release build..."
  - dotnet build "src/$PROJECT_NAME.sln" --nologo -c Release /p:Platform="Any CPU"
  artifacts:
    paths:
      - src/$PROJECT_RESULTS_NAME/bin/Release/**
    name: "Build Results"
code-quality:
  tags:
  - c#
  - windows
  stage: code-quality
  script:
  - echo "Running coding standards validation..."
  - cd "src/$PROJECT_NAME"
  - pwsh -File "Build/RunCodingStandardsValidation.ps1"
  artifacts:
    when: always
    paths:
      - src/$PROJECT_NAME/bin/Debug/net9.0-windows/CodeQuality/CodeQualityReport.xml
      - src/$PROJECT_NAME/bin/Release/net9.0-windows/CodeQuality/CodeQualityReport.xml
    reports:
      junit: 
        - src/$PROJECT_NAME/bin/Debug/net9.0-windows/CodeQuality/CodeQualityReport.xml
        - src/$PROJECT_NAME/bin/Release/net9.0-windows/CodeQuality/CodeQualityReport.xml
    name: "Code Quality Report"
    expire_in: 30 days
  dependencies:
  - build
  allow_failure: false

test:
  tags:
  - c#
  - windows
  stage: test
  script:
  - echo "starting tests"
  - dotnet test "src/$PROJECT_NAME.sln" --nologo -c Release /p:Platform="Any CPU"
  dependencies:
  - build
  - code-quality